"""initial schema

Revision ID: 5f6d154dfd91
Revises: 
Create Date: 2026-07-29 10:31:33.257241
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f6d154dfd91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('ktru_json', sa.Text(), nullable=False),
    sa.Column('attributes_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'product_key', name='uq_company_productkey')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_company_id'), ['company_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.String(length=80), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('customer', sa.String(length=300), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('submission_close', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=30), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('requirements_json', sa.Text(), nullable=False),
    sa.Column('synonyms_json', sa.Text(), nullable=False),
    sa.Column('card_json', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=32), nullable=False),
    sa.Column('source_updated_at', sa.Integer(), nullable=True),
    sa.Column('change_status', sa.String(length=12), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'purchase_id', name='uq_product_purchase')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_product_id'))
        batch_op.drop_index(batch_op.f('ix_leads_company_id'))

    op.drop_table('leads')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_company_id'))

    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_company_id'))

    op.drop_table('products')
    op.drop_table('companies')
    # ### end Alembic commands ###
