"""lead lot_json

Revision ID: fc81b9af4565
Revises: 2da31bef5d05
Create Date: 2026-07-31 10:23:17.087221
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc81b9af4565'
down_revision: Union[str, None] = '2da31bef5d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot_json', sa.Text(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('lot_json')

    # ### end Alembic commands ###
